package net.runelite.client.plugins.bankstander;

public enum bankstanderState
{
	ANIMATING,
	BANK_NOT_FOUND,
	DEPOSIT_ALL,
	DEPOSIT_EXCEPT,
	FIND_BANK,
	ITERATING,
	MISSING_ITEMS,
	TIMEOUT,
	CLOSE_BANK,
	WITHDRAW_ITEMS,
	USING_ITEM_ON_ITEM,
	USING_ITEM,
	USING_TOOL_ON_ITEM
}
